name: "RealQuestions"
description: "RealQuestions Australia"

<<<<<<< HEAD
url: "http://localhost:4000"
#baseurl: "https://realquestions.net.au/fbapp"
=======
#url: "http://localhost:4000"
baseurl: "https://realquestions.net.au"
>>>>>>> origin/develop
# paginate: 10
# gems: [jekyll-paginate]
# paginate_path: "page:num"

markdown: kramdown
permalink: pretty
highlighter: pygments.rb
